library(shiny)
library(shinyWidgets)
library(shinyhelper)
library(shinyjs)
library(plotly)
library(DT)
library(AachenColorPalette)
library(forcats)
library(scales)
library(dplyr)
library(tibble)
library(purrr)
library(ggplot2)
library(tidyr)
library(fgsea)
library(readr)
library(stringr)
library(cowplot)
library(shinycssloaders)

theme_set(theme_cowplot())

# load static data
contrasts = readRDS("data/study_contrasts.rds")
ranks = readRDS("data/study_ranks.rds")
overview = readRDS("data/study_overview.rds")
progeny = readRDS("data/PROGENy_results.rds")
dorothea = readRDS("data/dorothea_results.rds")
gsea = readRDS("data/GSEA_results.rds")
mi_gsea = readRDS("data/GSEA_mir_results.rds")
directed_signature = readRDS("data/signature.rds")
undirected_signature = readRDS("data/fisher_signature.rds")

example_geneset = read_csv("data/multiple_geneset.csv")
